site_name: Raj Garg
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: deep-purple
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to Dark Mode
  font:
    code: Roboto Mono
  features:
    - navigation.instant
  plugins:
    - search
    - search.suggest
    - search.highlight
    - social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/rajgarg021
      - icon: fontawesome/brands/twitter
        link: https://x.com/rajgarg021
