site_name: Raj Garg
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    scheme: slate
    primary: blue-grey
    accent: indigo

  font:
    code: Roboto Mono

  plugins:
    - search
    - search.suggest
    - search.highlight
    - social

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rajgarg021
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/rajgarg021
    - icon: fontawesome/solid/paper-plane
      link: mailto:rajgarg021@gmail.com
