site_name: Raj Garg
theme:
  name: material
  palette:
    scheme: slate
    primary: amber
  font:
    code: Roboto Mono
  features:
    - navigation.instant
  plugins:
    - search
    - search.suggest
    - search.highlight
  markdown_extensions:
    - pymdownx.pathconverter:
        base_path: / # default: ''
        relative_path: docs/ # default ''
        absolute: false # default: false
        tags: 'a script img link object embed'
  # nav:
  #   - Home: index.md
  #   - Resume: docs/resume.md
