site_name: Raj Garg
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    scheme: slate
    primary: indigo
    accent: blue

  font:
    code: Roboto Mono
  
  plugins:
    - search
    - search.suggest
    - search.highlight
    - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rajgarg021
    - icon: fontawesome/brands/twitter
      link: https://x.com/rajgarg021
